# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import principal_resource
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        TelaPrincipal.setObjectName("TelaPrincipal")
        TelaPrincipal.resize(440, 290)
        TelaPrincipal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(TelaPrincipal)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet(
            "background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.selectAllEmbarqueButton = QtWidgets.QPushButton(
            self.centralwidget)
        self.selectAllEmbarqueButton.setEnabled(True)
        self.selectAllEmbarqueButton.setGeometry(
            QtCore.QRect(200, 210, 111, 21))
        self.selectAllEmbarqueButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectAllEmbarqueButton.setStyleSheet("background-color: auto;")
        self.selectAllEmbarqueButton.setIconSize(QtCore.QSize(100, 30))
        self.selectAllEmbarqueButton.setCheckable(False)
        self.selectAllEmbarqueButton.setObjectName("selectAllEmbarqueButton")
        self.addFuncButton = QtWidgets.QPushButton(self.centralwidget)
        self.addFuncButton.setEnabled(True)
        self.addFuncButton.setGeometry(QtCore.QRect(100, 30, 111, 23))
        self.addFuncButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addFuncButton.setStyleSheet("background-color: auto;")
        self.addFuncButton.setIconSize(QtCore.QSize(100, 30))
        self.addFuncButton.setCheckable(False)
        self.addFuncButton.setObjectName("addFuncButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 50, 50))
        self.label.setStyleSheet("background-color: auto;\n"
                                 "image: url(:/principal/icons/business_application_addmale_useradd_insert_add_user_client_2312.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.deleteFuncButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteFuncButton.setEnabled(True)
        self.deleteFuncButton.setGeometry(QtCore.QRect(100, 90, 111, 23))
        self.deleteFuncButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteFuncButton.setStyleSheet("background-color: auto;")
        self.deleteFuncButton.setIconSize(QtCore.QSize(100, 30))
        self.deleteFuncButton.setCheckable(False)
        self.deleteFuncButton.setObjectName("deleteFuncButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 70, 50, 50))
        self.label_10.setStyleSheet(
            "image: url(:/principal/icons/delete_delete_deleteusers_delete_male_user_maleclient_2348.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 130, 50, 50))
        self.label_11.setStyleSheet(
            "image: url(:/principal/icons/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.updateFuncButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateFuncButton.setEnabled(True)
        self.updateFuncButton.setGeometry(QtCore.QRect(100, 150, 111, 23))
        self.updateFuncButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateFuncButton.setStyleSheet("background-color: auto;")
        self.updateFuncButton.setIconSize(QtCore.QSize(100, 30))
        self.updateFuncButton.setCheckable(False)
        self.updateFuncButton.setObjectName("updateFuncButton")
        self.deleteEmbarqueButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteEmbarqueButton.setEnabled(True)
        self.deleteEmbarqueButton.setGeometry(QtCore.QRect(300, 90, 111, 23))
        self.deleteEmbarqueButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteEmbarqueButton.setStyleSheet("background-color: auto;")
        self.deleteEmbarqueButton.setIconSize(QtCore.QSize(100, 30))
        self.deleteEmbarqueButton.setCheckable(False)
        self.deleteEmbarqueButton.setObjectName("deleteEmbarqueButton")
        self.updateEmbarqueButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateEmbarqueButton.setEnabled(True)
        self.updateEmbarqueButton.setGeometry(QtCore.QRect(300, 150, 111, 23))
        self.updateEmbarqueButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateEmbarqueButton.setStyleSheet("background-color: auto;")
        self.updateEmbarqueButton.setIconSize(QtCore.QSize(100, 30))
        self.updateEmbarqueButton.setCheckable(False)
        self.updateEmbarqueButton.setObjectName("updateEmbarqueButton")
        self.addEmbarqueButton = QtWidgets.QPushButton(self.centralwidget)
        self.addEmbarqueButton.setEnabled(True)
        self.addEmbarqueButton.setGeometry(QtCore.QRect(300, 30, 111, 23))
        self.addEmbarqueButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addEmbarqueButton.setStyleSheet("background-color: auto;")
        self.addEmbarqueButton.setIconSize(QtCore.QSize(100, 30))
        self.addEmbarqueButton.setCheckable(False)
        self.addEmbarqueButton.setObjectName("addEmbarqueButton")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(240, 130, 50, 50))
        self.label_14.setStyleSheet(
            "image: url(:/principal/icons/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(130, 190, 50, 50))
        self.label_17.setStyleSheet(
            "image: url(:/principal/icons/male-user-search_25352.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 50, 50))
        self.label_2.setStyleSheet("background-color: auto;\n"
                                   "image: url(:/principal/icons/business_application_addmale_useradd_insert_add_user_client_2312.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(240, 70, 50, 50))
        self.label_18.setStyleSheet(
            "image: url(:/principal/icons/delete_delete_deleteusers_delete_male_user_maleclient_2348.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        TelaPrincipal.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TelaPrincipal)
        self.statusbar.setObjectName("statusbar")
        TelaPrincipal.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(TelaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        self.menuA = QtWidgets.QMenu(self.menubar)
        self.menuA.setObjectName("menuA")
        TelaPrincipal.setMenuBar(self.menubar)
        self.actionCadastrarFuncionario = QtWidgets.QAction(TelaPrincipal)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ":/principal/icons/business_application_addmale_useradd_insert_add_user_client_2312.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrarFuncionario.setIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionCadastrarFuncionario.setFont(font)
        self.actionCadastrarFuncionario.setObjectName(
            "actionCadastrarFuncionario")
        self.actionEditar_Funcionario = QtWidgets.QAction(TelaPrincipal)
        self.actionEditar_Funcionario.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ":/principal/icons/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar_Funcionario.setIcon(icon1)
        self.actionEditar_Funcionario.setObjectName("actionEditar_Funcionario")
        self.actionExcluir_Funcionario = QtWidgets.QAction(TelaPrincipal)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            ":/principal/icons/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExcluir_Funcionario.setIcon(icon2)
        self.actionExcluir_Funcionario.setObjectName(
            "actionExcluir_Funcionario")
        self.actionConsultar_Funcionarios = QtWidgets.QAction(TelaPrincipal)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(
            ":/principal/icons/male-user-search_25352.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConsultar_Funcionarios.setIcon(icon3)
        self.actionConsultar_Funcionarios.setObjectName(
            "actionConsultar_Funcionarios")
        self.actionadd = QtWidgets.QAction(TelaPrincipal)
        self.actionadd.setObjectName("actionadd")
        self.menuA.addAction(self.actionCadastrarFuncionario)
        self.menubar.addAction(self.menuA.menuAction())

        self.retranslateUi(TelaPrincipal)
        self.actionCadastrarFuncionario.triggered.connect(
            self.addFuncButton.click)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipal)

    def retranslateUi(self, TelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrincipal.setWindowTitle(_translate("TelaPrincipal", "MainWindow"))
        self.selectAllEmbarqueButton.setText(
            _translate("TelaPrincipal", "Consultar Embarque"))
        self.addFuncButton.setText(_translate(
            "TelaPrincipal", "Adicionar Funcionario "))
        self.deleteFuncButton.setText(_translate(
            "TelaPrincipal", "Remover Funcionario"))
        self.updateFuncButton.setText(_translate(
            "TelaPrincipal", "Editar Funcionario"))
        self.deleteEmbarqueButton.setText(
            _translate("TelaPrincipal", "Remover Embarque"))
        self.updateEmbarqueButton.setText(
            _translate("TelaPrincipal", "Editar Embarque"))
        self.addEmbarqueButton.setText(_translate(
            "TelaPrincipal", "Adicionar Embarque"))
        self.menuA.setTitle(_translate("TelaPrincipal", "A"))
        self.actionCadastrarFuncionario.setText(
            _translate("TelaPrincipal", "CadastrarFuncionario"))
        self.actionCadastrarFuncionario.setToolTip(
            _translate("TelaPrincipal", "Cadastrar um Funcionario"))
        self.actionEditar_Funcionario.setText(
            _translate("TelaPrincipal", "Editar Funcionario"))
        self.actionEditar_Funcionario.setToolTip(
            _translate("TelaPrincipal", "Editar um Funcionário"))
        self.actionExcluir_Funcionario.setText(
            _translate("TelaPrincipal", "Excluir Funcionario"))
        self.actionExcluir_Funcionario.setToolTip(
            _translate("TelaPrincipal", "Excluir um Funcionário"))
        self.actionConsultar_Funcionarios.setText(
            _translate("TelaPrincipal", "Consultar Funcionarios"))
        self.actionConsultar_Funcionarios.setToolTip(_translate(
            "TelaPrincipal", "Consultar todos os funcionários"))
        self.actionadd.setText(_translate("TelaPrincipal", "add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_TelaPrincipal()
    ui.setupUi(TelaPrincipal)
    TelaPrincipal.show()
    sys.exit(app.exec_())
